# Generated by Django 4.2 on 2023-09-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatividade',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
